### ISSUE TITLE
bug - command calm is broken

### ISSUE THREAD

**Issue by madtomic** [nickperkins/StableMaster#12]
I got a untamed donkey in front of me. bug?

![image](https://user-images.githubusercontent.com/6004542/58362921-01e69580-7e6b-11e9-9ced-115f729bc45a.png)

**Comment by RobotoRaccoon** [comment]
Calm is used for angry wolves.

**Comment by madtomic** [comment]
Ah, that explains the word calm. I thought it was typo and was suppose to be claim. Lol
