### ISSUE TITLE
feature - support for foxes and ocelots

### ISSUE THREAD

**Issue by VIXIVIXIV** [nickperkins/StableMaster#14]
With the addition of foxes and redesigned ocelots in 1.14, there are more pet mobs available, but unlike some of the other pet mobs (cats, parrots, wolves), they cannot teleport to the player in vanilla, making transporting them from their native biomes a pain.

If foxes and ocelots can trust a specific player, then they must have a variable stored with their entity data listing the trusted player's UUID, just like tamed mobs. Even if the variable has a different name, an exception via an if statement that only triggers for those mob types can easily be implemented.

Alternatively, make it so the plugin automatically searches for a "trusted player UUID" field so that if Mojang adds more trust-only mobs, the plugin won't need as much updating.

**Comment by RobotoRaccoon** [comment]
I can't see the listing in the Javadocs for trusted players (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Fox.html)

Can you send me the link?

**Comment by nickperkins** [comment]
Trusted players are stored in an NBT Tag List https://www.digminecraft.com/data_tags/fox.php

**Comment by RobotoRaccoon** [comment]
There'll probably be no way to decide on who the true owner is if it's a list of players. Meaning anyone the fox trusts could steal it from the original owner.

**Comment by nickperkins** [comment]
Without a one to one relationship between ocelot/fox you can't have ownership so I think this can be closed.
