### ISSUE TITLE
Limiting Use

### ISSUE THREAD

**Issue by HewDaily** [nickperkins/StableMaster#7]
Thanks for a great plugin.  As a server owner, I'm always looking out for how any amount of grief can happen and where.  I can not have any level of player on our servers being able to "tame grief" with your plugin.

I love this plugin as a way to reward our best players, who I know won't "tame grief", and to give them extra piece of mind knowing they can leave their llamas and horses anywhere they like.

Can you add a permission that players must have in order to claim animals with this plugin?

**Comment by RobotoRaccoon** [comment]
Animal claiming is done with vanilla ownership. The only thing I can do for that is add a permission in order to tame the animal, thus they need the permission in order to own and command it

**Comment by HewDaily** [comment]
Absolutely, that's exactly what I'm talking about:  they need a permission to own and command it with your plugin.  Vanilla taming is fine because the animal isn't owned, it's just tamed (except for wolves and cats of course).

**Comment by RobotoRaccoon** [comment]
I'm assuming that update is what you wanted? Permissions to disable/enable the taming of animals

**Comment by HewDaily** [comment]
Thank you so much!  Obviously I can't wait for the next release!

**Comment by RobotoRaccoon** [comment]
There's a pre-release jar here, for now: https://github.com/RobotoRaccoon/StableMaster/releases/

**Comment by HewDaily** [comment]
We tried the pre-release last night and what you added is definitely something some server owners would use because you stopped ALL taming.  That's cool.

However, I was talking about allowing regular Minecraft taming but not allowing StableMaster protected taming unless someone had the permission.  So a player without StableMaster permissions can run around and tame all the horses they want but those horses can easily be ridden by someone else (basic MC taming).  Only when someone gets the StableMaster permission do they get everything your plugin offers.

**Comment by RobotoRaccoon** [comment]
StableMaster taming is directly linked to the vanilla ownership of the horse. I tried setting owner to null whilst tamed to true, but it did not like that one bit.
So to get around that, I would have to treat every user as a rider to the horse that's tamed by someone without said permission, but no one else would still be able to claim it as their own. Or, whenever someone else rides it, instantly set them to the owner, which can be abused. I don't see a simple way to resolve that whilst still maintaining the simple claiming mechanism

**Comment by HewDaily** [comment]
Hey, sorry, I didn't get an email notification from github.  Anyways, I totally understand - thanks for checking into it.  I'm curious though because I don't know the details: when you say taming is directly linked to vanilla ownership of the horse are you saying that, internally, Minecraft/Spigot makes a note of who the player was that tamed the horse?  So, in vanilla, even though anyone can ride a tamed horse the data is there about who was the original person who tamed the horse?

**Comment by RobotoRaccoon** [comment]
Yeah, Minecraft has built-in ownership of animals that can be tamed. Normally this ownership only affects cats and dogs, but this plugin uses it to decide who is the owner of horses too.
My issue was setting an animal to be tamed (rideable) but not owned, but it didn't like this one bit. I'd have to change my whole mechanism of ownership to add this feature and I'm not sure it's the path I want to go down with this plugin, in regards to ease of claiming ownership.
I've also started back up at university recently so I have to prioritise my efforts elsewhere for the moment.
