### ISSUE TITLE
Fire Bad!

### ISSUE THREAD

**Issue by QuazarShark** [nickperkins/StableMaster#8]
**Describe the bug**
Installed plugin on multiplayer server running MC 1.13.2 and Spigot, both fire, fire tick, and lava still damage tamed pets even with correctly configured .config settings. Other damages tested (creeper explosions, player melee) protected as expected. Other damage types untested.

**To Reproduce**
1. Go to: multiplayer server(??)
2. Spawn and tame unfortunate dog
3. Fly, teleport dog to you when over lava to make sure it's not registered as player damage, or set a fire and push dog into it
4. RIP dog :(

**Expected behavior**
Dog is ok (but dog is NOT)

**Server version:**
Spigot 1.13.2

**StableMaster Version**
Whatever newest version is at the time of this posting, not sure where to look this up sorry.

**Comment by RobotoRaccoon** [comment]
Can you post your config.yml?

**Comment by QuazarShark** [comment]
The server host has also been messing with it as we tried to figure out what was wrong, so I don't know what the current configuration is exactly but we switched true false back and forth and it didn't seem to have any effect even after a /sm reload x_x

[config.yml.zip](https://github.com/RobotoRaccoon/StableMaster/files/2685730/config.yml.zip)

**Comment by RobotoRaccoon** [comment]
I can't replicate what I think you're saying.
Using that config I set a tamed dog on fire, and push it into lava, and it does not take any damage

**Comment by RobotoRaccoon** [comment]
I'm still unable to replicate this.
